apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: multitool
  namespace: lesson211
spec:
  selector:
    matchLabels:
      name: multitool
  template:
    metadata:
      labels:
        name: multitool
    spec:
      containers:
      - name: multitool
        image: praqma/network-multitool
        command: ['sh', '-c', 'sleep infinity']
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
        - name: shared
          mountPath: /shared
          readOnly: true
        env:
        - name: HTTP_PORT
          value: "8080"
      volumes:
        - name: shared
          hostPath:
            path: /var/log
