apiVersion: v1
kind: Pod
metadata:
  name: task21
  namespace: lesson21
spec:
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'while true; do echo $(date) >> /shared/tmp.txt && sleep 5; done']
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
    - name: shared
      mountPath: /shared
    env:
    - name: HTTP_PORT
      value: "8080"
  - name: multitool
    image: praqma/network-multitool
    command: ['sh', '-c', 'sleep infinity']
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
      - name: shared
        mountPath: /shared
  volumes:
    - name: shared
      emptyDir: {}
